import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import vm from "node:vm";
const replayPath = resolve(import.meta.dirname, process.argv[2] || "replay_WereMF_260522_235200.json");
const run = JSON.parse(await readFile(replayPath, "utf8"));
const expectedPlayers = run.report.playerNames.length;
const receiver = run.report.playerNames[0];
const appEl={innerHTML:""},toastEl={textContent:"",classList:{add(){},remove(){}}};
const document={querySelector:s=>s==="#app"?appEl:s==="#toast"?toastEl:null,querySelectorAll:()=>[]};
const storage=new Map();
const context=vm.createContext({console,document,URLSearchParams,setTimeout,clearTimeout,location:{search:"",protocol:"http:",host:"127.0.0.1"},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},navigator:{clipboard:{writeText:async()=>{}}},WebSocket:class{static OPEN=1;}});
const source=await readFile(new URL("../WereMFWeb/src/app.js",import.meta.url),"utf8");
vm.runInContext(`${source}\n;globalThis.__ui={state,onMessage,render};`,context);
for(const entry of run.events.filter(x=>x.receiver===receiver))context.__ui.onMessage(entry.message);
context.__ui.render();
const {state}=context.__ui,html=appEl.innerHTML;
const checks={terminal:state.phase==="终局",remappedPlayerId:state.playerId!==state.players.findIndex?.(()=>false),players:state.players.length===expectedPlayers,entities:state.entities.length===expectedPlayers,realNamesRestored:run.report.playerNames.every(name=>state.players.some(p=>p.name===name)&&html.includes(name)),noAnonymousNamesAtEnd:!state.players.some(p=>/^玩家\d+$/.test(p.name)),ownRoleVisible:html.includes(state.role),eventsRendered:state.events.length>40,noUndefined:!html.includes("undefined"),winnerRendered:state.events.some(x=>x.text.includes("游戏结束"))};
checks.remappedPlayerId=Number.isInteger(state.playerId)&&state.playerId>=1&&state.playerId<=expectedPlayers;
checks.gameSeatShown=html.includes("game-seat")&&html.includes("本局编号")&&html.includes(`<b>${state.playerId}</b>`);
const ok=Object.values(checks).every(Boolean);console.log(JSON.stringify({ok,receiver,checks,summary:{playerId:state.playerId,role:state.role,phase:state.phase,players:state.players.map(p=>p.name),events:state.events.length}},null,2));process.exit(ok?0:1);
