import { cp, mkdir, rm } from "node:fs/promises";
import { resolve } from "node:path";
const root = resolve(import.meta.dirname, "..");
const dist = resolve(root, "dist");
const server = resolve(root, "..", "WereMFServer", "wwwroot");
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(resolve(root, "src"), dist, { recursive: true });
await rm(server, { recursive: true, force: true });
await mkdir(server, { recursive: true });
await cp(dist, server, { recursive: true });
console.log(`Built WereMF Web → ${dist}`);
