module WereMF.Module.Api

open System.Text.RegularExpressions

let private toSnakeCase (s: string) =
    Regex.Replace(s, "(?<=.)([A-Z])", "_$1").ToLower()

type ApiType =
    | CommandError
    | RollInitError
    | RollBarNotEnough
    | RollBarError
    | RollBoomNotEnough
    | RollBoomError
    | PlayerDeadBroadcast
    | PlayerDeadRebornBroadcast
    | PlayerDeadRevealBroadcast
    | LeafDeadP1Broadcast
    | LeafDeadP2Broadcast
    | PlayerRebornNotify
    | TntBoomBroadcast
    | XiansongBoomBroadcast
    | MyzIgnoreBroadcast
    | PaoxianPartyNotify
    | MyzThreatenBlockBroadcast
    | PendingSkillCreated
    | MyzThreatFailedNotify
    | MyzThreatenForceNotify
    | MyzThreatenNotify
    | InvalidPendingSkillNotify
    | DogeInvolveBroadcast
    | JiaohuaVoteBlockBroadcast
    | RequestJiaohuaVoteBlock
    | RequestKirbyUsingCopySkill
    | RequestFenxiaReborn
    | RequestCtfReborn
    | RequestCaimonReborn
    | RequestJiangxianRealVote
    | RequestJiangxianDeadVote
    | JiaohuaSkillFailedBySmog
    | JiaohuaSkillResultNotify
    | RequestJiaohuaSkill
    | DogeSuicideBroadcast
    | RequestDogeSkillForceThreaten
    | RequestDogeSkill
    | DoctorSkillBroadcast
    | DoctorSaveBroadcast
    | RequestDoctorSkill
    | MoleSkillSuccessNotify
    | RequestMoleRedGround
    | MoleRedTwiceNotify
    | MoleSkillFailNotify
    | MoleRedTwiceBroadcast
    | MoleKillBroadcast
    | MoleKillSpringBroadcast
    | RequestMoleSkill
    | RabiMilkedNotify
    | RequestDrinkMilk
    | RabiMilkTypeNotify
    | RabiKillBroadcast
    | RequestRabiSkillForceThreaten
    | RequestRabiSkill
    | RequestShelangSkill
    | FamaoSkillBroadcast
    | FamaoReverseFailedBroadcast
    | FamaoReversedBroadcast
    | FamaoSaveBroadcast
    | RequestFamaoSkill
    | KirbySkillFailBySpringNotify
    | KirbySkillFailByDogeNotify
    | KirbySkillFailByInvalidCharaNotify
    | KirbySkillSuccessCharaNotify
    | RequestKirbySkill
    | FenxiaSkillNoFenNotify
    | FenxiaSkillFailedByDogeNotify
    | FenxiaSkillFailedByUnknownDeadNotify
    | FenxiaSkillFailedBySmogNotify
    | FenxiaSkillFailedByInvalidCharaNotify
    | FenxiaSkillSuccessCharaNotify
    | RequestFenxiaSkill
    | CreeperSkillFailByDogeNotify
    | RequestCreeperSkill
    | PaoxianSkillFailByDogeNotify
    | PaoxianKillBroadcast
    | PaoxianKillSpringBroadcast
    | RequestPaoxianSkill
    | ShiwuSkillFailByDogeNotify
    | ShiwuKidnapBroadcast
    | ShiwuBroadcastFailedNotify
    | ShiwuBroadcastCharaBroadcast
    | ShiwuBroadcastResultBroadcast
    | ShiwuKidnappedSkillDisabledNotify
    | ShiwuExposedKillBroadcast
    | RequestShiwuSkill
    | HuikaSkillFailByDogeNotify
    | HuikaSmogBroadcast
    | HuikaSmogKillBroadcast
    | GameUpdateNight
    | RequestHuikaSkill
    | YinmoSkillFailByDogeNotify
    | YinmoKillBroadcast
    | YinmoKillSpringBroadcast
    | RequestYinmoSkill
    | CtfSkillFailByDogeNotify
    | RequestCtfSkill
    | RequestHechongCopyLeaf
    | HechongSkillFailBySmogNotify
    | HechongSkillFailByLeafNotify
    | HechongSkillFailByInvalidCharaNotify
    | HechongSkillSuccessCopyNotify
    | RequestHechongSkill
    | CaimonSkillNoCaiNotify
    | CaimonSkillFailByDogeNotify
    | RequestCaimonSkillForceThreaten
    | RequestCaimonSkill
    | XiansongSkillFailByDogeNotify
    | RequestXiansongGiveMfa
    | XiansongGetMfaSmogNotify
    | XiansongGetMfaNotify
    | XiansongGetMfaFailNotify
    | RequestXiansongSkillForceThreaten
    | RequestXiansongSkill
    | RequestJiangxianSkill
    | MyzSelfRevealBroadcast
    | MyzThreatFailedByAlreadyNotify
    | MyzThreatFailedByNoSkillNotify
    | RequestMyzSkillForceThreaten
    | RequestMyzSkill
    | RequestPlayerList
    | PlayerInit
    | RequestLeafGame
    | RequestAnonymousGame
    | PlayerNotifyChara
    | RequestRerollPlayer
    | PlayerNotifyCharaReset
    | RequestLeafCharas
    | LeafNotifyFirstChara
    | RequestLeafCharaReroll
    | LeafNotifyFirstCharaReroll
    | NightStartBroadcast
    | GameWinBroadcast
    | GameWinSummary
    | SkillFailBySuddenDeathNotify
    | SkillFailByUnexpectedBehavior
    | SkillFailByLeafProtectedNotify
    | SkillFailByKirbyNotify
    | KirbyGetSkillNotify
    | SkillExecuteFailNotify
    | SkillBlockedByJiaohuaNotify
    | NightSummaryBroadcast
    | NightSummaryQueuedBroadcast
    | BugKillBroadcast
    | DayStartBroadcast
    | GameUpdateDay
    | JiaohuaDeadSkillBroadcast
    | RequestJiaohuaDeadSkill
    | ShiwuInvolveBroadcast
    | BaiduBroadcast
    | BaiduResultBroadcast
    | VoteStartBroadcast
    | GameUpdateVote
    | RequestVote
    | VoteEndBroadcast
    | JiaohuaSuicideBroadcast
    | VoteResultBroadcast
    | VoteTieBroadcast
    | VoteBaiduFailBroadcast
    | BarleaderNotify
    | JiaohuaStartNotify
    | XiansongStartNotify
    | RequestForNextGame
    | CliNightSummary
    | CliDaySummary
    | CliGameSeed
    | ParseError of ApiType
    member this.ToSnakeString () =
        match this with
        | ParseError t -> $"{t.ToString() |> toSnakeCase }_parse_error"
        | value -> value.ToString () |> toSnakeCase
