<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <PublishSingleFile>true</PublishSingleFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FSharpPlus" Version="1.9.1" />
    </ItemGroup>
    
    <ItemGroup>
        <Compile Include="Type\Chara.fs" />
        <Compile Include="Type\Role.fs" />
        <Compile Include="Type\Player.fs" />
        <Compile Include="Type\Skill.fs" />
        <Compile Include="Type\Entity.fs" />
        <Compile Include="State\RollState.fs" />
        <Compile Include="State\NightState.fs" />
        <Compile Include="State\GameState.fs" />
        <Compile Include="State\MainState.fs" />
        <Compile Include="Game\Cli.fs" />
        <Compile Include="Game\Send.fs" />
        <Compile Include="Game\JiaoHua.fs" />
        <Compile Include="Game\PaoXian.fs" />
        <Compile Include="Game\Leaf.fs" />
        <Compile Include="Game\Bind.fs" />
        <Compile Include="Update\Init.fs" />
        <Compile Include="Update\Roll.fs" />
        <Compile Include="Update\Night.fs" />
        <Compile Include="Program.fs" />
        <EmbeddedResource Include="config.json" />
    </ItemGroup>

</Project>
