<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <PublishSingleFile>true</PublishSingleFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FSharpPlus" Version="1.9.1" />
    </ItemGroup>
    
    <ItemGroup>
        <Compile Include="Common\Chara.fs" />
        <Compile Include="Common\Role.fs" />
        <Compile Include="Common\Player.fs" />
        <Compile Include="Common\Roll.fs" />
        <Compile Include="Common\Entity.fs" />
        <Compile Include="Common\Skill.fs" />
        <Compile Include="State\NightState.fs" />
        <Compile Include="State\DayState.fs" />
        <Compile Include="State\GameState.fs" />
        <Compile Include="State\MainState.fs" />
        <Compile Include="Module\Cli.fs" />
        <Compile Include="Module\RollModule.fs" />
        <Compile Include="Module\RoleModule.fs" />
        <Compile Include="Module\EntityModule.fs" />
        <Compile Include="Module\SkillModule.fs" />
        <Compile Include="Module\GameModule.fs" />
        <Compile Include="Role\JiaoHua.fs" />
        <Compile Include="Role\Doge.fs" />
        <Compile Include="Role\Doctor.fs" />
        <Compile Include="Role\Mole.fs" />
        <Compile Include="Role\Rabi.fs" />
        <Compile Include="Role\SheLang.fs" />
        <Compile Include="Role\FaMao.fs" />
        <Compile Include="Role\Kirby.fs" />
        <Compile Include="Role\FenXia.fs" />
        <Compile Include="Role\Creeper.fs" />
        <Compile Include="Role\PaoXian.fs" />
        <Compile Include="Role\ShiWu.fs" />
        <Compile Include="Role\HuiKa.fs" />
        <Compile Include="Role\YinMo.fs" />
        <Compile Include="Role\CTF.fs" />
        <Compile Include="Role\HeChong.fs" />
        <Compile Include="Role\CaiMon.fs" />
        <Compile Include="Role\XianSong.fs" />
        <Compile Include="Role\JiangXian.fs" />
        <Compile Include="Role\Myz.fs" />
        <Compile Include="Role\Leaf.fs" />
        <Compile Include="Role\Bind.fs" />
        <Compile Include="Skill\JiaoHua.fs" />
        <Compile Include="Skill\Doge.fs" />
        <Compile Include="Skill\Doctor.fs" />
        <Compile Include="Skill\Mole.fs" />
        <Compile Include="Skill\Rabi.fs" />
        <Compile Include="Skill\SheLang.fs" />
        <Compile Include="Skill\FaMao.fs" />
        <Compile Include="Skill\Kirby.fs" />
        <Compile Include="Skill\FenXia.fs" />
        <Compile Include="Skill\Creeper.fs" />
        <Compile Include="Skill\PaoXian.fs" />
        <Compile Include="Skill\ShiWu.fs" />
        <Compile Include="Skill\HuiKa.fs" />
        <Compile Include="Skill\YinMo.fs" />
        <Compile Include="Skill\CTF.fs" />
        <Compile Include="Skill\HeChong.fs" />
        <Compile Include="Skill\CaiMon.fs" />
        <Compile Include="Skill\XianSong.fs" />
        <Compile Include="Skill\JiangXian.fs" />
        <Compile Include="Skill\Myz.fs" />
        <Compile Include="Skill\Bind.fs" />
        <Compile Include="Update\Init.fs" />
        <Compile Include="Update\RollUpdate.fs" />
        <Compile Include="Update\NightUpdate.fs" />
        <Compile Include="Update\DayUpdate.fs" />
        <Compile Include="Update\GameUpdate.fs" />
        <Compile Include="Program.fs" />
        <EmbeddedResource Include="config.json" />
    </ItemGroup>

</Project>
