export function room({ state, e, soundToggleButton }) {
  const seats = [...state.players]; while (seats.length < Math.max(7, state.players.length)) seats.push(null);
  const settings = state.roomSettings;
  const settingsPanel = state.isHost ? `<form class="room-settings" id="room-settings"><label>普通请求限时<input class="input" id="setting-request-timeout" type="number" min="5" max="600" value="${settings.requestTimeoutSeconds}"/><span>秒</span></label><label>每名可投票玩家时长<input class="input" id="setting-vote-per-alive" type="number" min="5" max="600" value="${settings.voteSecondsPerAlive}"/><span>秒</span></label><label>每次投票扣减<input class="input" id="setting-vote-penalty" type="number" min="0" max="600" value="${settings.votePenaltySeconds}"/><span>秒</span></label><label>连续消息展示间隔<input class="input" id="setting-event-interval" type="number" min="0" max="10" value="${settings.eventIntervalSeconds}"/><span>秒</span></label><button class="btn btn-ghost" type="submit">保存房间设置</button></form>` : `<div class="settings-summary">普通请求 ${settings.requestTimeoutSeconds}s · 投票每人 ${settings.voteSecondsPerAlive}s · 每票扣 ${settings.votePenaltySeconds}s · 消息间隔 ${settings.eventIntervalSeconds}s</div>`;
  return `<main class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">MF</span> MF 杀 ONLINE</div><div class="top-actions">${soundToggleButton()}<div class="status"><span class="status-dot ${state.connected ? "" : "off"}"></span>${state.connected ? "房间在线" : "连接中断"}</div><button class="btn btn-ghost leave-room" data-leave-room>彻底退出</button></div></header>
  <section class="room-head"><div><div class="eyebrow">私人房间</div><div class="room-code" id="copy-room-code" role="button" tabindex="0">${e(state.roomCode)} <small>点击复制</small></div></div><button class="btn btn-ghost" id="copy-room">复制邀请信息</button></section>
  <section class="lobby"><div class="panel"><div class="panel-title"><h2>玩家席位</h2><span class="count">${state.players.length} / 16</span></div><div class="players-grid">${seats.map((p,i) => p ? `<div class="player-seat ${p.connected ? "" : "offline"}"><span class="seat-no">${p.id}</span><div>${e(p.name)}${p.isHost ? '<span class="host-tag">房主</span>' : ""}${p.isBot ? '<span class="bot-tag">BOT</span>' : ""}${p.id === state.playerId ? '<span class="you-tag">你</span>' : ""}</div></div>` : `<div class="player-seat empty-seat"><span class="seat-no">${i+1}</span><div>等待加入</div></div>`).join("")}</div></div>
  <aside class="panel"><div class="panel-title"><h3>开局之前</h3></div><p class="lobby-note">需要至少 <strong>7 名玩家</strong>。开始后，系统会私下发送身份与行动面板。建议所有人保持页面开启，并在语音或线下完成白天讨论。</p><div class="divider"></div><p class="lobby-note">你是 <strong>${state.isHost ? "房主" : `${state.playerId} 号玩家`}</strong>${state.isHost ? "，玩家到齐后由你开局。" : "，等待房主开局。"}</p>${settingsPanel}${state.isHost ? `<div class="bot-controls"><button class="btn btn-ghost" data-add-bot ${state.players.length >= 16 ? "disabled" : ""}>＋ 增加 Bot</button><button class="btn btn-ghost" data-remove-bot ${state.players.some(p=>p.isPermanentBot) ? "" : "disabled"}>－ 删除 Bot</button></div>` : ""}<div class="start-wrap">${state.isHost ? `<button class="btn btn-primary" id="start-game" ${state.players.length < 7 ? "disabled" : ""}>${state.players.length < 7 ? `还差 ${7-state.players.length} 人` : "所有人准备好 · 开始"}</button>` : `<button class="btn" disabled>等待房主开始</button>`}</div></aside></section></main>`;
}
function entityFor(id) { return state.entities.find(x => (x.player?.id ?? x.player?.Id) === id); }
