import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { loadWebApp } from "./web-app-fixture.mjs";
const replayPath = resolve(import.meta.dirname, process.argv[2] || "replay_WereMF_260522_235200.json");
const run = JSON.parse(await readFile(replayPath, "utf8"));
const expectedPlayers = run.report.playerNames.length;
const receiver = run.report.playerNames[0];
const { ui, appEl } = await loadWebApp();
for(const entry of run.events.filter(x=>x.receiver===receiver)) ui.onMessage(entry.message);
ui.render();
const {state}=ui,html=appEl.innerHTML;
const checks={terminal:state.phase==="终局",remappedPlayerId:state.playerId!==state.players.findIndex?.(()=>false),players:state.players.length===expectedPlayers,entities:state.entities.length===expectedPlayers,realNamesRestored:run.report.playerNames.every(name=>state.players.some(p=>p.name===name)&&html.includes(name)),noAnonymousNamesAtEnd:!state.players.some(p=>/^玩家\d+$/.test(p.name)),ownRoleVisible:html.includes(state.role),eventsRendered:state.events.length>40,noUndefined:!html.includes("undefined"),winnerRendered:state.events.some(x=>x.text.includes("游戏结束"))};
checks.remappedPlayerId=Number.isInteger(state.playerId)&&state.playerId>=1&&state.playerId<=expectedPlayers;
checks.gameSeatShown=html.includes("game-seat")&&html.includes("本局编号")&&html.includes(`<b>${state.playerId}</b>`);
const ok=Object.values(checks).every(Boolean);console.log(JSON.stringify({ok,receiver,checks,summary:{playerId:state.playerId,role:state.role,phase:state.phase,players:state.players.map(p=>p.name),events:state.events.length}},null,2));process.exit(ok?0:1);
